
// Text cleaning and filtering utility
export const cleanExtractedText = (rawText: string): string => {
  console.log('Starting text cleaning. Original length:', rawText.length);
  
  let cleanedText = rawText;
  
  // Remove binary/garbled characters and non-printable characters
  cleanedText = cleanedText.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g, '');
  
  // Remove common PDF artifacts and metadata
  cleanedText = cleanedText.replace(/(?:Producer|Creator|CreationDate|ModDate|Title|Subject|Keywords):\s*[^\n]*/gi, '');
  
  // Split into lines for line-by-line filtering
  const lines = cleanedText.split('\n');
  const filteredLines = lines.filter(line => {
    const trimmedLine = line.trim();
    
    // Skip empty lines or lines with only whitespace
    if (trimmedLine.length === 0) return false;
    
    // Remove page headers/footers patterns
    if (/^page\s+\d+(\s+of\s+\d+)?$/i.test(trimmedLine)) return false;
    if (/^\d+\s*$/.test(trimmedLine) && trimmedLine.length < 4) return false; // Standalone page numbers
    
    // More specific navigation removal - only exact matches
    if (/^(table of contents|index|contents)$/i.test(trimmedLine)) return false;
    if (/^(continued|see page|page \d+)$/i.test(trimmedLine)) return false;
    
    // Increased thresholds for header/footer patterns to preserve section headers
    if (/^(home inspection|inspection report|property inspection)/i.test(trimmedLine) && trimmedLine.length < 100) return false;
    if (/^(report date|inspection date|client|inspector)/i.test(trimmedLine) && trimmedLine.length < 120) return false;
    
    // Remove copyright and legal disclaimers
    if (/copyright|©|\(c\)|all rights reserved|proprietary|confidential/i.test(trimmedLine)) return false;
    if (/this report|liability|warranty|disclaimer|limitation/i.test(trimmedLine) && trimmedLine.length > 100) return false;
    
    // Remove contact information patterns
    if (/^(phone|tel|fax|email|website|www\.|http)/i.test(trimmedLine)) return false;
    if (/\b\d{3}[-.)]\s*\d{3}[-.)]\s*\d{4}\b/.test(trimmedLine) && trimmedLine.length < 50) return false; // Phone numbers
    
    // Remove lines that are mostly special characters or formatting
    if (/^[^\w\s]*$/.test(trimmedLine)) return false;
    if (trimmedLine.length > 5 && /^[_\-=.*#]{5,}$/.test(trimmedLine)) return false;
    
    // Remove common PDF generation artifacts
    if (/^(generated by|created with|pdf|adobe)/i.test(trimmedLine) && trimmedLine.length < 50) return false;
    
    // Preserve lines with important inspection keywords
    if (/\b(defect|repair|recommend|safety|issue|concern|damage|replace|inspect)\b/i.test(trimmedLine)) return true;
    
    return true;
  });
  
  // Rejoin the filtered lines
  cleanedText = filteredLines.join('\n');
  
  // Remove excessive whitespace
  cleanedText = cleanedText.replace(/\n{3,}/g, '\n\n'); // Replace 3+ line breaks with 2
  cleanedText = cleanedText.replace(/[ \t]{2,}/g, ' '); // Replace multiple spaces/tabs with single space
  
  cleanedText = cleanedText.trim();
  
  const reductionPercentage = ((rawText.length - cleanedText.length) / rawText.length * 100);
  
  console.log('Text cleaning completed. Cleaned length:', cleanedText.length);
  console.log('Size reduction:', reductionPercentage.toFixed(1) + '%');
  
  // Fallback protection: if we removed more than 80% of content, something went wrong
  if (reductionPercentage > 80) {
    console.log('WARNING: Text reduction too aggressive, using lighter cleaning');
    // Fall back to minimal cleaning - just remove binary chars and excessive whitespace
    let lightCleaning = rawText;
    lightCleaning = lightCleaning.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g, '');
    lightCleaning = lightCleaning.replace(/\n{3,}/g, '\n\n');
    lightCleaning = lightCleaning.replace(/[ \t]{2,}/g, ' ');
    return lightCleaning.trim();
  }
  
  return cleanedText;
};
