// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znohkixqcmwifqnqwdoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpub2hraXhxY213aWZxbnF3ZG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjYxMzQsImV4cCI6MjA2MzUwMjEzNH0.NQjkuT7wrT-LonrJDIsdmJLf6T06KA9PStelWz0bPtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);